# LogHarbor Processor Configuration
kafka:
  bootstrap_servers: "localhost:9092"
  topic: "logs"
  group_id: "log-processor-group"
  auto_offset_reset: "earliest"
  enable_auto_commit: true
  auto_commit_interval_ms: 1000
  session_timeout_ms: 30000
  heartbeat_interval_ms: 3000

elasticsearch:
  url: "http://localhost:9200"
  index: "logs"
  sniff: false
  healthcheck: false

websocket:
  port: "8080"
  read_buffer_size: 1024
  write_buffer_size: 1024

health:
  port: "8081" 